---
--- Enumerations
--- 


CREATE TYPE public.kehadiran_type AS ENUM (
    'sakit',
    'izin',
    'alfa'
);


--- Mata Pelajaran
--- Mata Pelajaran objek mata pelajaran.
CREATE TABLE public.mata_pelajaran (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    kode text NOT NULL,
    tingkat int NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.mata_pelajaran OWNER TO school;

ALTER TABLE ONLY public.mata_pelajaran 
    ADD CONSTRAINT mata_pelajaran_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mata_pelajaran ADD CONSTRAINT mata_pelajaran_kode_unique UNIQUE (kode);

--- Jam Pelajaran
--- Jam Pelajaran objek jam pelajaran.
CREATE TABLE public.jam_pelajaran (
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_matpel int NOT NULL,
    jam_mulai timestamp with time zone,
    jam_akhir timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.jam_pelajaran OWNER TO school;

ALTER TABLE ONLY public.jam_pelajaran 
    ADD CONSTRAINT jam_pelajaran_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jam_pelajaran
    ADD CONSTRAINT jam_pelajaran_mata_pelajaran_id_matpel_foreign FOREIGN KEY (id_matpel) REFERENCES public.mata_pelajaran(id);


--- Kelas
--- Kelas objek kelas.
CREATE TABLE public.kelas (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    tingkat int NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.kelas OWNER TO school;

ALTER TABLE ONLY public.kelas 
    ADD CONSTRAINT kelas_pkey PRIMARY KEY (id);


--- Wali Kelas
--- Wali Kelas objek wali kelas.
CREATE TABLE public.wali_kelas (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    alamat text,
    telpon text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.wali_kelas OWNER TO school;

ALTER TABLE ONLY public.wali_kelas 
    ADD CONSTRAINT wali_kelas_pkey PRIMARY KEY (id);


--- Siswa
--- Siswa objek siswa.
CREATE TABLE public.siswa (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    id_kelas int NOT NULL,
    id_wali_kelas int NOT NULL,
    tingkat int NOT NULL,
    alamat text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.siswa OWNER TO school;

ALTER TABLE ONLY public.siswa 
    ADD CONSTRAINT siswa_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT kelas_siswa_id_kelas_foreign FOREIGN KEY (id_kelas) REFERENCES public.kelas(id);

ALTER TABLE ONLY public.siswa
    ADD CONSTRAINT wali_kelas_siswa_id_wali_kelas_foreign FOREIGN KEY (id_wali_kelas) REFERENCES public.wali_kelas(id);


--- Jam Pelajaran Siswa
--- Jam Pelajaran Siswa objek jam pelajaran.
CREATE TABLE public.jam_pelajaran_siswa (
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_jam_pelajaran int NOT NULL,
    id_siswa int NOT NULL,
    status kehadiran_type NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.jam_pelajaran_siswa OWNER TO school;

ALTER TABLE ONLY public.jam_pelajaran_siswa 
    ADD CONSTRAINT jam_pelajaran_siswa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT jam_pelajaran_jam_pelajaran_siswa_id_jam_pelajaran_foreign FOREIGN KEY (id_jam_pelajaran) REFERENCES public.jam_pelajaran(id);

ALTER TABLE ONLY public.jam_pelajaran_siswa
    ADD CONSTRAINT siswa_jam_pelajaran_siswa_id_siswa_foreign FOREIGN KEY (id_siswa) REFERENCES public.siswa(id);

--- User
--- User objek user.
CREATE TABLE public.user (
    id int GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    alamat int NOT NULL,
    password int NOT NULL,
    telepon int NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.user OWNER TO school;

ALTER TABLE ONLY public.user 
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--- User Siswa
--- User objek user siswa.
CREATE TABLE public.user_siswa (
    id int GENERATED BY DEFAULT AS IDENTITY,
    id_user int NOT NULL,
    id_siswa int NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

ALTER TABLE public.user_siswa OWNER TO school;

ALTER TABLE ONLY public.user_siswa 
    ADD CONSTRAINT user_siswa_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_siswa
    ADD CONSTRAINT user_user_siswa_id_user_foreign FOREIGN KEY (id_user) REFERENCES public.user(id);

ALTER TABLE ONLY public.user_siswa
    ADD CONSTRAINT siswa_user_siswa_id_siswa_foreign FOREIGN KEY (id_siswa) REFERENCES public.siswa(id);
